# Generated by Django 3.0.5 on 2020-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_name', models.ManyToManyField(to='ecom.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='SubCategory_name',
            field=models.ManyToManyField(to='ecom.SubCategory'),
        ),
    ]
