# Generated by Django 3.0.5 on 2020-05-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20200510_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='SubCategory_name',
            new_name='subcategory_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory_name',
        ),
    ]
