# Generated by Django 3.0.5 on 2020-05-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20200510_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ManyToManyField(to='ecom.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_name',
            field=models.ManyToManyField(to='ecom.SubCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_name',
            field=models.ManyToManyField(to='ecom.Category'),
        ),
    ]
