# Generated by Django 3.0.5 on 2020-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20200512_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ManyToManyField(blank=True, to='ecom.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_name',
            field=models.ManyToManyField(blank=True, to='ecom.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.ManyToManyField(blank=True, to='ecom.Category'),
        ),
    ]
